export default {
    SUCCESS: `Operation is completed`,
    SOMETHING_WENT_WRONG: `Something went wrong!`,
    NOT_FOUND: (entity: string) => `${entity} is not found`,
    TOO_MANY_REQUESTS: `So many requests`,
    UNAUTHORIZED: 'You are not allowed to perform this task',
    SESSION_EXPIRED: 'Your session has expired. Please log in again.',
    FORBIDDEN: 'You do not have permission to perform this task.',

    auth: {
        ALREADY_EXISTS: (entity: string, identifier: string) => `${identifier} already exists for the ${entity}`,
        ALREADY_CONFIRMED: (entity: string) => `${entity} already CONFIRMED`,
        INVALID_PHONE_NUMBER: `Invalid phone number`,
        USER_REGISTERED: `Account has been created successfully.`,
        USER_NOT_EXIST: `Account does not exist`,
        INVALID_EMAIL_OR_PASSWORD: `Invalid email or password`,
        LOGIN_SUCCESSFUL: `Login successful`
    },
    school: {
        SCHOOL_REGISTERED: `School registered successfully.`,
        SCHOOL_VERIFICATION_SENT: `School verification email has been sent.`,
        SCHOOL_VERIFIED: `School has been verified successfully.`,
        SCHOOL_NOT_VERIFIED: `School is not verified yet. Please verify via email.`,
        INVITATION_SENT: `Invitation email sent successfully.`,
        INVITATION_ACCEPTED: `Invitation accepted successfully.`,
        CLASS_CREATED: `Class created successfully.`,
        SECTION_ADDED: `Section added successfully.`,
        ACADEMIC_CONFIG_UPDATED: `Academic configuration updated successfully.`,
        SEMESTER_ADVANCED: `Semester advanced successfully.`,
        ACADEMIC_YEAR_ROLLED_OVER: `Academic year rolled over successfully.`,
        STAFF_CREATED: `Staff member created successfully.`,
        STAFF_UPDATED: `Staff member updated successfully.`,
        STUDENT_CREATED: `Student created successfully.`,
        STUDENT_APPROVED: `Student approved successfully.`,
        GR_ALREADY_EXISTS: `GR number already exists for this school.`,
        ADMISSION_CREATED: `Admission created successfully.`,
        ATTENDANCE_CREATED: `Attendance recorded successfully.`,
        FEE_REMINDER_CREATED: `Fee reminders scheduled successfully.`,
        FEE_SLIP_CREATED: `Fee slips generated successfully.`,
        FEE_INVOICE_CREATED: `Fee invoice created successfully.`,
        FEE_INVOICE_UPDATED: `Fee invoice updated successfully.`,
        FEE_INVOICE_PAYMENT_RECORDED: `Invoice payment recorded successfully.`,
        FEE_INVOICES_BULK_CREATED: `Fee invoices generated successfully.`,
        FEE_EXPENSE_CREATED: `Expense entry added successfully.`,
        FEE_EXPENSE_UPDATED: `Expense entry updated successfully.`,
        EXAM_CREATED: `Exam created successfully.`,
        EXAM_RESULT_SAVED: `Exam results saved successfully.`,
        EQUIPMENT_CREATED: `Equipment record created successfully.`,
        EQUIPMENT_ISSUED: `Equipment issued successfully.`,
        EQUIPMENT_RETURNED: `Equipment returned successfully.`,
        LIBRARY_BOOK_CREATED: `Library book created successfully.`,
        LIBRARY_BOOK_ISSUED: `Library book issued successfully.`,
        LIBRARY_BOOK_RETURNED: `Library book returned successfully.`,
        TEMPLATE_CREATED: `Template created successfully.`,
        TEST_MESSAGE_SENT: `Test message sent successfully.`,
        WHATSAPP_CAMPAIGN_CREATED: `WhatsApp campaign saved successfully.`
    }
}
